<?php
namespace LCTest;

use Fake\Fake;
use Monolog\Logger;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-03-25 at 11:03:44.
 */
class LCTestTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var LCTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new LCTest;
    }

    /**
     * @covers LCTest::__toString
     */
    public function test__toString() {
        $this->assertSame((string)$this->object, "I'm a test for Fake");
    }

    /**
     * @covers LCTest::getFake
     */
    public function testGetFake() {
        $fake = $this->object->getFake();
        $this->assertSame((string)$fake, "Io sono " . Fake::class);
    }
    
    /**
     * @covers LCTest::getFakeFactory
     */
    public function testGetFakeFactory() {
        $factory = $this->object->getFakeFactory();
        $fake = $factory->getFake();
        $logger = $fake->testDependency();
        $this->assertSame($logger->getName(), 'Fake Log');
    }
}
